# Generated by Django 5.2 on 2025-04-25 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contratos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_contrato', models.CharField(max_length=100)),
                ('nome_empresa', models.CharField(max_length=100)),
                ('objeto', models.CharField(max_length=100)),
                ('sei', models.CharField(max_length=100)),
                ('gestor', models.CharField(max_length=100)),
                ('fiscal', models.CharField(max_length=100)),
                ('data_i', models.DateField()),
                ('data_f', models.DateField()),
                ('vigencia', models.IntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=100)),
            ],
        ),
        migrations.CreateModel(
            name='Visualizar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_contrato', models.CharField(max_length=100)),
                ('mes', models.CharField(max_length=100)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('acumulado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('restante', models.DecimalField(decimal_places=2, max_digits=10)),
                ('porcem', models.FloatField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
